#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nguyenthaison
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quanlybenhnhan")]
	public partial class QuanLyBenhNhanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbenhnhan(benhnhan instance);
    partial void Updatebenhnhan(benhnhan instance);
    partial void Deletebenhnhan(benhnhan instance);
    partial void Insertdichvu(dichvu instance);
    partial void Updatedichvu(dichvu instance);
    partial void Deletedichvu(dichvu instance);
    #endregion
		
		public QuanLyBenhNhanDataContext() : 
				base(global::Nguyenthaison.Properties.Settings.Default.quanlybenhnhanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBenhNhanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBenhNhanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBenhNhanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBenhNhanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<benhnhan> benhnhans
		{
			get
			{
				return this.GetTable<benhnhan>();
			}
		}
		
		public System.Data.Linq.Table<dichvu> dichvus
		{
			get
			{
				return this.GetTable<dichvu>();
			}
		}
		
		public System.Data.Linq.Table<dangkidichvu> dangkidichvus
		{
			get
			{
				return this.GetTable<dangkidichvu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.benhnhan")]
	public partial class benhnhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabn;
		
		private string _hoten;
		
		private string _gioitinh;
		
		private string _ngaysinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabnChanging(int value);
    partial void OnmabnChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    #endregion
		
		public benhnhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mabn
		{
			get
			{
				return this._mabn;
			}
			set
			{
				if ((this._mabn != value))
				{
					this.OnmabnChanging(value);
					this.SendPropertyChanging();
					this._mabn = value;
					this.SendPropertyChanged("mabn");
					this.OnmabnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dichvu")]
	public partial class dichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _madichvu;
		
		private string _tendichvu;
		
		private double _dongia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadichvuChanging(int value);
    partial void OnmadichvuChanged();
    partial void OntendichvuChanging(string value);
    partial void OntendichvuChanged();
    partial void OndongiaChanging(double value);
    partial void OndongiaChanged();
    #endregion
		
		public dichvu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madichvu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int madichvu
		{
			get
			{
				return this._madichvu;
			}
			set
			{
				if ((this._madichvu != value))
				{
					this.OnmadichvuChanging(value);
					this.SendPropertyChanging();
					this._madichvu = value;
					this.SendPropertyChanged("madichvu");
					this.OnmadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendichvu", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string tendichvu
		{
			get
			{
				return this._tendichvu;
			}
			set
			{
				if ((this._tendichvu != value))
				{
					this.OntendichvuChanging(value);
					this.SendPropertyChanging();
					this._tendichvu = value;
					this.SendPropertyChanged("tendichvu");
					this.OntendichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Float NOT NULL")]
		public double dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dangkidichvu")]
	public partial class dangkidichvu
	{
		
		private int _mabn;
		
		private int _madichvu;
		
		private string _ngaydangki;
		
		public dangkidichvu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabn", DbType="Int NOT NULL")]
		public int mabn
		{
			get
			{
				return this._mabn;
			}
			set
			{
				if ((this._mabn != value))
				{
					this._mabn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madichvu", DbType="Int NOT NULL")]
		public int madichvu
		{
			get
			{
				return this._madichvu;
			}
			set
			{
				if ((this._madichvu != value))
				{
					this._madichvu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangki", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ngaydangki
		{
			get
			{
				return this._ngaydangki;
			}
			set
			{
				if ((this._ngaydangki != value))
				{
					this._ngaydangki = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
